<a href="https://colab.research.google.com/github/misael1062/Introduccion_a_Python-Curso_Online/blob/main/calculo_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MISAEL ALVAREZ GARCIA

##OPTOMECANICA

###OP-501

####26/02/2021

In [25]:
#EJERCICIOS RESUELTOS EN CLASE 

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets

In [2]:
def funcion1(x):
    y = 2*x+5 - np.sin(x)
    return y

In [3]:
funcion1(3)

10.858879991940134

In [18]:
def matriz_desplazamiento(d):
    matriz = np.matrix([ [1, d] , [0, 1] ])
    return matriz
def matriz_superficie_plana(n1, n2):
    matriz = np.matrix([ [1, 0] , [0, n1/n2] ])
    return matriz

def matriz_superficie_curva(n1, n2, radio):
    matriz = np.matrix([ [1, 0] , [-(n2-n1)/(n2*radio) , n1/n2 ]])
    return matriz

In [19]:
from IPython.display import display, Markdown

In [24]:
#EJERCICIOS CLASE ANTERIOR
#ejercicio inciso A)
V0 = np.matrix('3; 0.05')
M1 = matriz_desplazamiento(5)
Vf = M1 * V0
display(Markdown('# El resultado del A) es '))
print(Vf)

#Ejercicio inciso B)
V1 = np.matrix('3; 0.05')
M1_5 = matriz_desplazamiento(10)
Vf = M1_5 * V1
display(Markdown('# El resultado del B) es '))
print(Vf)

#Ejercicio inciso C)
V3 = np.matrix('3; 0.05')
M2 = matriz_superficie_plana(1, 1.3)
Vf = M2 * V3
display(Markdown('# El resultado del C) es '))
print(Vf)

#Ejercicio inciso D)
V4 = np.matrix('3; 0.05')
M3 = matriz_superficie_plana(1.5, 1)
Vf = M3 * V4
display(Markdown('# El resultado del D) es '))
print(Vf)

#Ejrcicio inciso E)
V5 = np.matrix('3; 0.05')
M4 = matriz_superficie_curva(1, 1.3, 4)
Vf = M4 * V5
display(Markdown('# El resultado del e) es '))
print(Vf)

#Ejercicio inciso F)
V6 = np.matrix('3; 0.05')
M5 = matriz_superficie_curva(1.5, 1, -3)
Vf = M5 * V6
display(Markdown('# El resultado del F) es '))
print(Vf)

#Ejercicio inciso G)
V6 = np.matrix('3; 0.05')
M6_1 = matriz_desplazamiento(5)
M6_2 = matriz_superficie_plana(1, 1.4)
M6_3 = matriz_desplazamiento(5)
V1 = M6_1 * V6
V2 = M6_2 * V1
V3 = M6_3 * V2
#Vf = M5
display(Markdown('# El resultado del G) es '))
print(V3)
#print(M6_1*M6_2*M6_3*V6)
print('La matriz correcta es esta')
print(M6_3*M6_2*M6_1*V6)


# El resultado del A) es 

[[3.25]
 [0.05]]


# El resultado del B) es 

[[3.5 ]
 [0.05]]


# El resultado del C) es 

[[3.        ]
 [0.03846154]]


# El resultado del D) es 

[[3.   ]
 [0.075]]


# El resultado del e) es 

[[ 3.        ]
 [-0.13461538]]


# El resultado del F) es 

[[ 3.   ]
 [-0.425]]


# El resultado del G) es 

[[3.42857143]
 [0.03571429]]
La matriz correcta es esta
[[3.42857143]
 [0.03571429]]


En un sistema de multiples matrices, el resultado de todas las matrices intermedias es lo que se conoce como matriz equivalente del sistema

In [26]:
#En el G) la matriz equivalente 
M_equivalente = M6_3*M6_2*M6_1
print(M_equivalente)

#Con esto podemos calcular el resultado al cambiar las condicionales iniciales

[[1.         8.57142857]
 [0.         0.71428571]]


In [33]:
#Vamos a hacer un ejemplo de una celda interactiva
#ipywidgets.interact(matriz_desplazamiento, d = [0,10,1])

#funcion lambda
#Lambda x,y : lo que haga la funcion con las variables x , y
#Si quiero que la funcion haga x+y lo escribo como
#lambda x,y : x + y
ipywidgets.interact(lambda y0, angulo0 : M_equivalente*np.matrix([[y0], [angulo0]]) , #aqui termina el primer argumento
                    y0 =(-2, 2, 0.1), #Seundo argumento
                    angulo0 = (-0.1, 0.1, 0.01)) #Tercer argumento

interactive(children=(FloatSlider(value=0.0, description='y0', max=2.0, min=-2.0), FloatSlider(value=0.0, desc…

<function __main__.<lambda>>